site_name: SLADE Scripting Documentation
# repo_url: https://github.com/sirjuddington/SLADE
edit_uri: ''
docs_dir: 'mkdocs'
site_dir: '../../dist/res/docs/Scripting'
use_directory_urls: false
theme: readthedocs

extra_css:
  - 'css/slade.css'

markdown_extensions:
  - admonition

pages:
- Home: index.md
- Examples:
  - Open Archive: 'md/Examples/OpenArchive.md'
- Namespaces:
  - SLADE: 'md/Namespaces/SLADE.md'
  - Archives: 'md/Namespaces/Archives.md'
  - Game: 'md/Namespaces/Game.md'
  - MapEditor: 'md/Namespaces/MapEditor.md'
- Types:
  - Archive: 'md/Types/Archive.md'
  - ArchiveEntry: 'md/Types/ArchiveEntry.md'
  - ArchiveDir: 'md/Types/ArchiveDir.md'
  - EntryType: 'md/Types/EntryType.md'
  - ThingType: 'md/Types/ThingType.md'
  - Map: 'md/Types/Map.md'
  - MapEditor: 'md/Types/MapEditor.md'
  - ItemSelection: 'md/Types/ItemSelection.md'
  - MapObject: 'md/Types/MapObject.md'
