# Info
site_name: SLADE Scripting Documentation
repo_url: https://github.com/sirjuddington/SLADE
edit_uri: ''

# Settings
docs_dir: 'mkdocs'
site_dir: '../../dist/res/docs/Scripting'
use_directory_urls: false

# Theme
theme: readthedocs
theme_dir: 'theme'
extra_css:
  - 'css/slade.css'

# Extensions
markdown_extensions:
  - admonition

# Documentation Pages
pages:
- Home: index.md
- Examples:
  - Open Archive: 'md/Examples/OpenArchive.md'
  - Find Text In Entries: 'md/Examples/FindTextInEntries.md'
  - Change Textures: 'md/Examples/ChangeTextures.md'
  - Archvile Madness: 'md/Examples/ArchvileMadness.md'
- Namespaces:
  - slade: 'md/Namespaces/SLADE.md'
  - splashWindow: 'md/Namespaces/SplashWindow.md'
  - archives: 'md/Namespaces/Archives.md'
  - game: 'md/Namespaces/Game.md'
  - mapEditor: 'md/Namespaces/MapEditor.md'
- Types:
  - Archive: 'md/Types/Archive.md'
  - ArchiveFormat: 'md/Types/ArchiveFormat.md'
  - ArchiveEntry: 'md/Types/ArchiveEntry.md'
  - ArchiveDir: 'md/Types/ArchiveDir.md'
  - EntryType: 'md/Types/EntryType.md'
  - ThingType: 'md/Types/ThingType.md'
  - Map: 'md/Types/Map.md'
  - MapEditor: 'md/Types/MapEditor.md'
  - MapObject: 'md/Types/MapObject.md'
  - MapVertex: 'md/Types/MapVertex.md'
  - MapLine: 'md/Types/MapLine.md'
  - MapSide: 'md/Types/MapSide.md'
  - MapSector: 'md/Types/MapSector.md'
  - MapThing: 'md/Types/MapThing.md'
  - Colour: 'md/Types/Colour.md'
  - Plane: 'md/Types/Plane.md'
  - Point: 'md/Types/Point.md'
